<?php
# This file was automatically generated by the MediaWiki 1.33.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
        exit;
}

#$wgShowExceptionDetails = true;
#$wgDevelopmentWarnings = true; error_reporting( -1 ); ini_set( 'display_errors', 1);

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Tâi-oân-kì";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";
$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;


## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://www.taioanki.org";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
#$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

#$wgEmergencyContact = "apache@taioanki.org";
#$wgPasswordSender = "apache@taioanki.org";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBServer = "localhost";
$wgDBname = "taioanki";
$wgDBuser = "taioankiuser";
$wgDBpassword = "im12om2997yUi_";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];


## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
# target folder must be set with sudo chown -R www-data:www-data images/

#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# https://www.mediawiki.org/wiki/Topic:Qmkwqlxoor706ddt
#$wgTmpDirectory = "$wgResourceBasePath/images/tmp";
#$wgDebugToolbar = true;


# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "tai";

$wgSecretKey = "9bf35bdd45d26f2f86eba6422b0af86cd5c5e3da45041ff4f22162a671b3e921";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "0e17a33b1f31bcf8";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";


# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

#wfLoadExtension( 'MobileFrontend' );
#$wgMFMobileHeader = 'X-WAP';

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'MinervaNeue' );


## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Frequently_asked_questions#How_can_I_enable_it_on_my_own_(third-party)_wiki?
#$wgDefaultSkin = "vector-2022";
#$wgVectorDefaultSkinVersion = '2';
#$wgVectorDefaultSkinVersionForExistingAccounts = '2';
#$wgVectorDefaultSkinVersionForNewAccounts = '2';
#$wgVectorIsSearchInHeader = true;
#$wgVectorLanguageInHeader = true;
#$wgVectorUseWvuiSearch = true;

#https://www.mediawiki.org/wiki/Topic:Wtcbni0k7u3rzs6k
#$wgVectorDefaultSidebarVisibleForAuthorisedUser = true;
#$wgVectorDefaultSidebarVisibleForAnonymousUser = true;

#$wgMFDefaultSkinClass = 'SkinMinerva';
#$wgDefaultMobileSkin = 'minerva';

# End of automatically generated settings.
# Add more configuration options below.

# Disable anonymous editing
$wgGroupPermissions['*']['edit'] = false;

# Prevent new user registrations except by sysops
$wgGroupPermissions['*']['createaccount'] = true;

# Gives all registered users the ability to edit pages
$wgGroupPermissions['user']['edit'] = true;

# https://www.mediawiki.org/wiki/Extension:TemplateStyles
#wfLoadExtension( 'TemplateStyles' );

# https://www.mediawiki.org/wiki/Extension:Cite
#wfLoadExtension( 'Cite' );

# https://www.mediawiki.org/wiki/Manual:Image_administration#SVG
#$wgFileExtensions[] = 'svg';
#$wgAllowTitlesInSVG = true;
# Need librsvg2-bin
#$wgSVGConverter = 'rsvg';

# https://www.mediawiki.org/wiki/Extension:ConfirmEdit
#wfLoadExtensions([ 'ConfirmEdit', 'ConfirmEdit/QuestyCaptcha' ]);
#$wgCaptchaQuestions = [
#	'<b>鬥 nn̄g 粒 lián-á óa-khò ĕn-jín teh pháng ê 運輸器具  sī?</b>' => 'O͘-tó͘-bái',
#];

# https://www.mediawiki.org/wiki/Extension:Add_HTML_Meta_and_Title
#wfLoadExtension( 'AddHTMLMetaAndTitle' );

# https://www.mediawiki.org/wiki/Extension:ParserFunctions
#wfLoadExtension( 'ParserFunctions' );

# https://www.mediawiki.org/wiki/Extension:Renameuser
#wfLoadExtension( 'Renameuser' );

# https://www.mediawiki.org/wiki/Extension:Popups
#fLoadExtension( 'TextExtracts' );
#fLoadExtension( 'PageImages' );
#fLoadExtension( 'Popups' );

# https://www.mediawiki.org/wiki/Extension:WikiEditor
#fLoadExtension( 'WikiEditor' );

#https://www.mediawiki.org/wiki/Extension:CustomSubtitle
#fLoadExtension( 'CustomSubtitle' );

# https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Breaking_changes
$wgLogos = [
	'1x' => "/w/resources/assets/wiki.png",
	#'1.5x' => "path/to/1.5x_version.png",
	#'2x' => "path/to/2x_version.png",
	'svg' => "/w/resources/assets/wiki.svg",
	'icon' => "/w/resources/assets/wiki_icon.svg",  // A version of the logo without wordmark and tagline.
	'wordmark' => [
		'src' => "/w/resources/assets/wiki_wordmark.svg",
		'1x' => "/w/resources/assets/wiki_wordmark.png", // Recommended, but optional SVG logo for browsers with SVG support.
		'width' => 135,
		'height' => 22,
	],
	#'tagline' => [
	#	'src' => "path/to/tagline_version.png",
	#	'width' => 135,
	#	'height' => 15,
	#],
];

# https://www.mediawiki.org/wiki/Extension:MultiMaps
#equire_once "$IP/extensions/MultiMaps/MultiMaps.php";

$wgLocaltimezone = "Asia/Taipei";


#https://www.mediawiki.org/wiki/Manual:Using_custom_namespaces
#2025-11-07

define("DICTIONARY", 3000);
define("DICTIONARY_TALK", 3001);

$wgExtraNamespaces[DICTIONARY] = "Dictionary";
$wgExtraNamespaces[DICTIONARY_TALK] = "Dictionary_talk";
$wgNamespaceAliases["Sû-tián"] = DICTIONARY;
$wgNamespaceAliases["Sû-tián_talk"] = DICTIONARY_TALK;

# https://www.mediawiki.org/wiki/Extension:DarkMode
#wfLoadExtension( 'DarkMode' );

#$wgReadOnly = 'Chún-pī poaⁿ chhù';
